server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?characterEncoding=UTF-8&useSSL=false
    password: 123
    username: root


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.benqio.*.model


