server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/news?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
      # 初始连接数
    initialSize: 5
      # 最小连接池数量
    minIdle: 10
      # 最大连接池数量
    maxActive: 20
      # 配置获取连接等待超时的时间
    maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jackson:
    date-formate: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.java.*.model

Img:
  path: E:\IntelliJSpace\news\src\main\resources\static\img
  head_path: E:\IntelliJSpace\news\src\main\resources\static\img\headImg
  uploadFolder: E:\\IntelliJSpace\\news\\src\\main\\resources\\static\\img\\
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: false
  pageSize: pageHelperRows;
  supportMethodsArguments: false
